name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: git clone https://github.com/nassima2002/DEVOPS.git # Manually clone the repo

      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install php8.1 php8.1-mbstring php8.1-intl php8.1-bcmath php8.1-pdo php8.1-mysqli php8.1-xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-text
