name: PHPUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
      
      - name: Install PHP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php7.4 php7.4-mbstring php7.4-intl php7.4-bcmath php7.4-mysql php7.4-xml php7.4-curl unzip curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text
