name: PHPUnit TESTS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code (local)
        run: |
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git fetch origin ${{ github.ref }}
          git checkout ${{ github.sha }} # Correction de FETCH_HEAD

      - name: Install PHP and extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.1 php8.1-mbstring php8.1-intl php8.1-bcmath php8.1-mysql php8.1-xml php8.1-curl unzip curl

      - name: Check PHP version
        run: php -v

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install project dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text
