name: PHPUnit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y php8.1 php8.1-mbstring php8.1-intl php8.1-bcmath php8.1-mysql php8.1-xml php8.1-curl unzip curl

      - name: Check PHP version and extensions
        run: |
          php -v
          php -m

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install project dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text
