name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        run: |
          sudo apt-get update
          sudo apt-get install php8.1 php8.1-mbstring php8.1-intl php8.1-bcmath php8.1-pdo php8.1-mysqli php8.1-xdebug -y

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install Composer dependencies
        working-directory: ./ # ou ./nom_du_dossier_si_ton_code_est_dedans
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        working-directory: ./ # pareil ici
        run: vendor/bin/phpunit --coverage-text
